In [102]:
# Q1: Import NumPy and print its version.
import numpy as np
import pandas as pd

print("NumPy Version:", np.__version__)

df_clean = pd.read_csv('it_services_tickets_cleaned.csv',  low_memory=False)
for col in ['hours_logged', 'billing_rate_(usd)', 'billable_amount_usd', 'resolution_time_hours', 'csat_score']:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

matrix = df_clean[['hours_logged', 'billing_rate_(usd)', 'billable_amount_usd', 'resolution_time_hours', 'csat_score']].to_numpy()

NumPy Version: 2.2.6


In [53]:
# Q2: Make an array from the hours logged column.
hours_arr = matrix[:, 0]
# Explanation: Extracts hours logged column as a 1D NumPy array.

In [54]:
# Q3: Print the shape, the size and the data type of that array.
print(f"Shape: {hours_arr.shape}, Size: {hours_arr.size}, Dtype: {hours_arr.dtype}")
# Explanation: Shows shape, total element count, and data storage type of the array.

Shape: (48123,), Size: 48123, Dtype: float64


In [55]:
# Q4: Make an array of the numbers 1 to 50 using arange.
arr_1_50 = np.arange(1, 51)
print(arr_1_50)
# Explanation: Generates a sequence of integers from 1 to 50.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [56]:
# Q5: Make 10 evenly spaced numbers between 0 and 100 using linspace.
lin_arr = np.linspace(0, 100, 10)
print(lin_arr)
# Explanation: Creates 10 float values evenly spaced across the range [0, 100].

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [57]:
# Q6: Make an array of 10 zeros and an array of 10 ones.
zeros_arr = np.zeros(10)
ones_arr = np.ones(10)
print("Zeros:", zeros_arr)
print("Ones:", ones_arr)
# Explanation: Initializes 10-element array containing zeros and ones.

Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [58]:
# Q7: Make a 3 by 3 array of random numbers using seed 42.
np.random.seed(42)
rand_3x3 = np.random.rand(3, 3)
print(rand_3x3)
# Explanation: Sets random seed to 42 and create a 3x3 random matrix.

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [59]:
# Q8: Make a 2-D array from the hours logged and billing rate columns.
hours_rate_2d = matrix[:, :2]
print(hours_rate_2d[:5])
# Explanation: Makes the first two columns (hours and rates) into a 2D array matrix.

[[  nan 39.45]
 [ 1.34 33.15]
 [ 7.   48.1 ]
 [34.63 52.98]
 [12.76   nan]]


In [60]:
# Q9: Print how many dimensions that 2-D array has.
print("Dimensions:", hours_rate_2d.ndim)
# Explanation: Returns the total number of array dimensions = 2.

Dimensions: 2


In [61]:
# Q10: Print the first 5 values of the hours array.
print("First 5 hours:", hours_arr[:5])
# Explanation: Print the first five elements of the hours array.

First 5 hours: [  nan  1.34  7.   34.63 12.76]


In [62]:
# Q11: Print the last 5 values of the hours array.
print("Last 5 hours:", hours_arr[-5:])
# Explanation: Used negative indexing to select the lasts 5 elements.

Last 5 hours: [50.  4. 47.  2. nan]


In [63]:
# Q12: Print every second value from the first 20 values.
print("Every 2nd of first 20:", hours_arr[:20:2])
# Explanation: Print array with every 2 value from the first 20 entries.

Every 2nd of first 20: [   nan   7.    12.76    nan   1.66    nan  11.63  28.     0.59 253.85]


In [64]:
# Q13: Reverse the array.
reversed_hours = hours_arr[::-1]
# Explanation: Reverses element sequence from back to front using step -1.

In [65]:
# Q14: Find the sum of the hours array.
print("Sum of hours:", np.nansum(hours_arr))
# Explanation: Total cumulative sum of all logged hours.

Sum of hours: 2290016.55


In [66]:
# Q15: Find the mean, the minimum and the maximum of the hours array.
print(f"Mean: {np.nanmean(hours_arr):.2f}, Min: {np.nanmin(hours_arr)}, Max: {np.nanmax(hours_arr)}")
# Explanation: Calculates mean, min, max of logged hours.

Mean: 63.17, Min: -12.5, Max: 9888.01


In [67]:
# Q16: Find the standard deviation.
print("Standard Deviation:", np.nanstd(hours_arr))
# Explanation: Measures variance and spread of hours around its mean.

Standard Deviation: 493.3142529221527


In [68]:
# Q17: Find the median.
print("Median:", np.nanmedian(hours_arr))
# Explanation: Determines the middle value of hours.

Median: 13.1


In [69]:
# Q18: Count how many values are missing in the array.
print("Missing count:", np.isnan(hours_arr).sum())
# Explanation: Sums boolean indicators to find missing NaN values in the array.

Missing count: 11870


In [70]:
# Q19: Find the mean while ignoring the missing values.
print("NaN-ignoring Mean:", np.nanmean(hours_arr))
# Explanation: Calculates mean across non-null entries without NaNs.

NaN-ignoring Mean: 63.16764267784735


In [71]:
# Q20: Replace all the missing values with 0.
hours_no_nan = np.nan_to_num(hours_arr, nan=0.0)
print("Missing values in array after replacement:", np.isnan(hours_no_nan).sum())
# Explanation: Fills all NaN missing occurrences with 0.

Missing values in array after replacement: 0


In [72]:
# Q21: Count how many values are greater than 100.
print("Values > 100 count:", (hours_no_nan > 100).sum())
# Explanation: Calculates count of array elements greater than 100.

Values > 100 count: 1588


In [73]:
# Q22: Show only the values that are greater than 100.
print("Values > 100:", hours_no_nan[hours_no_nan > 100][:10])
# Explanation: Filters and displays values greater than 100.

Values > 100: [ 253.85  128.   1900.66  133.35  373.68 5000.    723.5   101.04  152.
  311.49]


In [74]:
# Q23: Show the values that are between 10 and 50.
print("Values between 10 & 50:", hours_no_nan[(hours_no_nan >= 10) & (hours_no_nan <= 50)][:10])
# Explanation: Values that are between 10 and 50.

Values between 10 & 50: [34.63 12.76 15.3  11.63 28.   10.16 32.71 30.84 18.   31.44]


In [75]:
# Q24: Count how many values are negative.
print("Negative values count:", (hours_no_nan < 0).sum())
# Explanation: Counting values less than zero.

Negative values count: 136


In [76]:
# Q25: Replace all the negative values with 0.
hours_no_nan[hours_no_nan < 0] = 0
print("Negative values count after fix:", (hours_no_nan < 0).sum())
# Explanation: Replace all the negative values with 0.

Negative values count after fix: 0


In [77]:
# Q26: Sort the array from smallest to largest.
sorted_hours = np.sort(hours_no_nan)
print("Sorted sample:", sorted_hours[:10])
# Explanation: Returns array elements sorted in ascending order.

Sorted sample: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [78]:
# Q27: Find the position of the largest value.
print("Index of max value:", np.argmax(hours_no_nan))
# Explanation: Identifies row index location containing maximum value.

Index of max value: 10041


In [79]:
# Q28: Find the position of the smallest value.
print("Index of min value:", np.argmin(hours_no_nan))
# Explanation: Identifies row index location containing minimum value.

Index of min value: 0


In [80]:
# Q29: Find the 5 largest values.
print("5 largest values:", np.partition(hours_no_nan, -5)[-5:])
# Explanation: Uses partial sorting to extract the top five largest values.

5 largest values: [8760.   8760.   8760.   9888.01 9888.01]


In [81]:
# Q30: Round every value to 1 decimal place.
rounded_hours = np.round(hours_no_nan, 1)
print(rounded_hours[:5])
# Explanation: Rounds all numbers in array to one decimal digit.

[ 0.   1.3  7.  34.6 12.8]


In [82]:
# Q31: Multiply every value by 2.
print(hours_no_nan[:5] * 2)
# Explanation: Performs multiplication by 2 on every value.

[ 0.    2.68 14.   69.26 25.52]


In [83]:
# Q32: Add 10 to every value.
print(hours_no_nan[:5] + 10)
# Explanation: Performs addition by 10 on every value.

[10.   11.34 17.   44.63 22.76]


In [84]:
# Q33: Multiply the hours array by the billing rate array.
rates_arr = np.nan_to_num(matrix[:, 1], nan=0.0)
calculated_billable = hours_no_nan * rates_arr
print("Calculated revenue sample:", calculated_billable[:5])
# Explanation: Performs element-wise multiplication between hours and rate arrays.

Calculated revenue sample: [   0.       44.421   336.7    1834.6974    0.    ]


In [85]:
# Q34: Check whether the two arrays have the same length.
print("Same length:", len(hours_no_nan) == len(rates_arr))
# Explanation: Evaluates equality of element count between two 1D arrays.

Same length: True


In [86]:
# Q35: Use np.where to mark values above 24 as slow and the rest as fast.
speed_labels = np.where(hours_no_nan > 24, 'slow', 'fast')
print("Speed classification sample:", speed_labels[:10])
# Explanation: Classifies items conditionally into categorical string outputs.

Speed classification sample: ['fast' 'fast' 'fast' 'slow' 'fast' 'fast' 'fast' 'fast' 'fast' 'fast']


In [87]:
# Q36: Make an array of the unique priority values.
priorities = df_clean['priority'].astype(str).to_numpy()
unique_priorities = np.unique(priorities)
print("Unique priorities:", unique_priorities)
# Explanation: Extracts distinct unique elements present in priority column.

Unique priorities: [' ' '--' '1' '2' '3' '4' 'CRITICAL' 'Critical' 'HIGH' 'High' 'LOW' 'Low'
 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4' 'PRIORITY' 'high'
 'low' 'medium' 'na' 'nan' 'p1' 'p2' 'p3' 'p4']


In [88]:
# Q37: Count how many times each unique priority value appears.
vals, counts = np.unique(priorities, return_counts=True)
for v, c in zip(vals, counts):
    print(f"Priority {v}: {c}")
# Explanation: Calculates distribution frequency for each unique priority state.

Priority  : 95
Priority --: 107
Priority 1: 1931
Priority 2: 1966
Priority 3: 1934
Priority 4: 1919
Priority CRITICAL: 1993
Priority Critical: 2000
Priority HIGH: 1950
Priority High: 2003
Priority LOW: 1945
Priority Low: 1840
Priority MEDIUM: 1949
Priority Medium: 1941
Priority P1: 1891
Priority P1 - Critical: 1969
Priority P2: 1907
Priority P3: 1950
Priority P4: 1880
Priority PRIORITY: 1
Priority high: 1971
Priority low: 1950
Priority medium: 2023
Priority na: 130
Priority nan: 1149
Priority p1: 1934
Priority p2: 1898
Priority p3: 1988
Priority p4: 1909


In [89]:
# Q38: Take the first 100 values and reshape them into a 10 by 10 array.
arr_10x10 = hours_no_nan[:100].reshape(10, 10)
print("10x10 Matrix Shape:", arr_10x10.shape)
# Explanation: Reshapes flat sequence of 100 elements into a 10x10 grid matrix.

10x10 Matrix Shape: (10, 10)


In [90]:
# Q39: Transpose that 10 by 10 array.
transposed_10x10 = arr_10x10.T
print("Transposed Shape:", transposed_10x10.shape)
# Explanation: Flips matrix axes, swapping rows into columns.

Transposed Shape: (10, 10)


In [91]:
# Q40: Flatten it back into a 1-D array.
flattened_arr = transposed_10x10.flatten()
print("Flattened Shape:", flattened_arr.shape)
# Explanation: Collapses 2D grid matrix back into a 1D vector structure.

Flattened Shape: (100,)


In [92]:
# Q41: Join two arrays together using np.concatenate.
concatenated = np.concatenate([hours_no_nan[:5], rates_arr[:5]])
print("Concatenated array:", concatenated)
# Explanation: Join two 1D arrays sequentially end-to-end.

Concatenated array: [ 0.    1.34  7.   34.63 12.76 39.45 33.15 48.1  52.98  0.  ]


In [93]:
# Q42: Split an array into 5 equal parts.
split_parts = np.array_split(hours_no_nan[:100], 5)
print("Number of split sections:", len(split_parts))
# Explanation: Splits input array evenly into 5 sub-arrays.

Number of split sections: 5


In [94]:
# Q43: Find the 25th, 50th and 75th percentile.
p25, p50, p75 = np.percentile(hours_no_nan, [25, 50, 75])
print(f"25th: {p25}, 50th: {p50}, 75th: {p75}")
# Explanation: Find quarter percentiles for hours array.

25th: 0.0, 50th: 6.57, 75th: 23.62


In [95]:
# Q44: Find the cumulative sum of the first 20 values.
cumsum_20 = np.cumsum(hours_no_nan[:20])
print("Cumulative sum output:", cumsum_20)
# Explanation: Returns running total sum across first 20 elements.

Cumulative sum output: [  0.     1.34   8.34  42.97  55.73  71.03  71.03  80.03  81.69  81.69
  81.69  83.13  94.76 167.07 195.07 205.23 205.82 212.82 466.67 470.87]


In [96]:
# Q45: Find the difference between each value and the one before it using np.diff.
diff_arr = np.diff(hours_no_nan[:10])
print("Differences sample:", diff_arr)
# Explanation: Find step differences between adjacent values.

Differences sample: [  1.34   5.66  27.63 -21.87   2.54 -15.3    9.    -7.34  -1.66]


In [97]:
# Q46: Keep every value inside the range 0 to 100 using np.clip.
clipped_hours = np.clip(hours_no_nan, 0, 100)
print(f"Min after clip: {clipped_hours.min()}, Max after clip: {clipped_hours.max()}")
# Explanation: Caps array elements outside strict range boundary 0 to 100.

Min after clip: 0.0, Max after clip: 100.0


In [98]:
# Q47: Convert the array to whole numbers.
int_hours = hours_no_nan.astype(int)
print("Integer format sample:", int_hours[:5])
# Explanation: Casts float array numbers into integer values.

Integer format sample: [ 0  1  7 34 12]


In [99]:
# Q48: Copy the array, change one value in the copy, and show that the original did not change.
original = hours_no_nan[:5].copy()
copied = original.copy()
copied[0] = 9999.0
print("Original first element:", original[0])
print("Copied first element:", copied[0])
# Explanation: Proves pass-by-value memory independence of NumPy `.copy()`.

Original first element: 0.0
Copied first element: 9999.0


In [100]:
# Q49: Save the array to a .npy file and load it back.
np.save('hours_array.npy', hours_no_nan)
loaded_hours = np.load('hours_array.npy')
print("Successfully loaded array shape:", loaded_hours.shape)
# Explanation: Saves NumPy array structure in system and reads it back.

Successfully loaded array shape: (48123,)


In [101]:
# Q50: Find the total revenue using np.dot on the hours array and the rate array.
total_revenue = np.dot(hours_no_nan, rates_arr)
print(f"Total Revenue: ${total_revenue:,.2f}")
# Explanation: Evaluate dot product to calculate total revenue.

Total Revenue: $127,427,757.53
